# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         SWF-Builder
version:      0.01
version_from: lib/SWF/Builder.pm
installdirs:  site
requires:
    Font::TTF::Font:               0.34
    SWF::Element:                  0.27

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
